language:
  - cpp
compiler:
  - gcc
script:
  - cmake ./ && make
  - bin/test_gabor_filter
  - bin/test_wavelet_converter
notifications:
  emails:
    - h-yaguchi@jsk.t.u-tokyo.ac.jp
  on_success: change
  on_failure: always
